---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

startUrl: https://ooffice.ddns.net

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

showStats: true
