version: '3'

services:
  elkarbackup:
    image: elkarbackup/elkarbackup:latest
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password-here"
      EB_CRON: "enabled"
    volumes:
      - /mnt/snapshot/elkar:/app/backups
      - uploads:/app/uploads
      - sshkeys:/app/.ssh
    ports:
      - 4000:80
    restart: unless-stopped
    
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "your-password-here"
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:
  # backups:
  uploads:
  sshkeys:
